### ISSUE TITLE
[DKG Engine] Only “usage” metrics are present for workloads

### ISSUE THREAD

**Issue by ktatarnikovhiro** [glaciation-heu/IceStream#184]
ENG: to provide workloads query in appendix. 

HIRO: The metrics that can be fetched are the following:

- CPU.Usage 
- CPU.Capacity 
- CPU.Allocated 
- RAM.Usage 
- RAM.Capacity 
- RAM.Allocated 
- Storage.Usage 
- Storage.Capacity 
- Storage.Allocated 
- Network.Usage 
- Energy.Usage

**Comment by ktatarnikovhiro** [comment]
[workloads.sparql.txt](https://github.com/user-attachments/files/17255507/workloads.sparql.txt)
[workloads.reponse.csv](https://github.com/user-attachments/files/17255535/workloads.reponse.csv)

**Comment by ktatarnikovhiro** [comment]
Matteo, could you with the help of the attached query configure remaining metrics, please? 
The attached query shows what is available in knowledge graph. (The usage metrics we still want to fetch from prometheus)

**Comment by mattG117** [comment]
Closing, solved in [updated queries](https://github.com/glaciation-heu/trade-off-service/commit/9f910d57555a7ba537a3969363fede9b2c519203)
