### ISSUE TITLE
[DKG] Max is missing for nodes

### ISSUE THREAD

**Issue by ktatarnikovhiro** [glaciation-heu/IceStream#185]
ENG: to provide nodes query in appendix. 

HIRO: Attached files contain Node metric queries. ***.Capacity** is a max metric for resource

- CPU.Capacity 
- CPU.Available 
- GPU.Capacity 
- RAM.Capacity 
- RAM.Available 
- Storage.Capacity 
- Storage.Available 
- Energy.Usage 
- Energy.Index 

[nodes.sparql.txt](https://github.com/user-attachments/files/17255628/nodes.sparql.txt)
[nodes.response.csv](https://github.com/user-attachments/files/17255629/nodes.response.csv)

**Comment by ktatarnikovhiro** [comment]
Matteo, Could you configure the Capacity as a `max` metric for a node.

**Comment by mattG117** [comment]
Closing, solved in [updated queries](https://github.com/glaciation-heu/trade-off-service/commit/9f910d57555a7ba537a3969363fede9b2c519203)
