### ISSUE TITLE
[DKG] Response of Trade-off service is not consistent with what is agreed with AI Decision Engine

### ISSUE THREAD

**Issue by ktatarnikovhiro** [glaciation-heu/IceStream#190]
ENG/LUH: to agree and clarify gaps, also please specify the details

**Comment by mattG117** [comment]
Closing, solved in [fixed nodes and workloads response](https://github.com/glaciation-heu/trade-off-service/commit/895d544d5919d8e0651718b3ccf3eacb31d44c07)

**Comment by mattG117** [comment]
@ktatarnikov Trade-Off Service response is compliant with what agreed and included in the [updated docs](https://github.com/glaciation-heu/IceStream/tree/trade_off_service_docs_updated/trade_off_service/docs)

**Comment by ktatarnikovhiro** [comment]
@armantorkzaban @AminKeshavarzi 
Could you please confirm that the referred API what you agreed with Mattheo?

**Comment by AminKeshavarzi** [comment]
We tried various queries but aren’t receiving any data on the validation cluster. Could you please first show us a demo on how to use this API? After that, we'll review the data.

**Comment by ktatarnikovhiro** [comment]
I am asking about not about actual data but the API formats - open API definition, request, response formats. Are they what you have agreed?
