### ISSUE TITLE
[DKG] Workloads are not configured with requests and limits for resources.

### ISSUE THREAD

**Issue by ktatarnikovhiro** [glaciation-heu/IceStream#191]
Workloads need to be configured with requests/limits explicitly for the containers with all resources: cpu/memory/ephemeral-storage/gpu

This is for those that has workloads ready: DELL/MEF

**Comment by ainnocenti2011** [comment]
For Use Case 1 Sogei/Mef, the capacity information can be found in the deployment.yaml (https://github.com/glaciation-heu/mef-sog-uc1/blob/main/workload-core/deployment.yaml). The resources allocated to the PODs, including the replicas for both microservices, are configured. Currently, we are building a historical record of two months of processing on these resources to support the WorkLoadPlacement/AI process. The running is a continuous process in the Validation Environment.

**Comment by ainnocenti2011** [comment]
For Use Case 1 Sogei/Mef The only unused parameter is the GPU one, as it's actually not needed:
GPU - 0:0

**Comment by parklize** [comment]
UC2 workload service has been configured for four resources: mem, cpu, gpu, storage
http://argocd.integration/applications/uc2-workload-service

**Comment by ktatarnikovhiro** [comment]
DELL is done, SOGEI is in progress
