### ISSUE TITLE
[DKG][TradeOffService] if the date range falls outside the actual data the APIs return InternalServerError

### ISSUE THREAD

**Issue by ktatarnikovhiro** [glaciation-heu/IceStream#192]
Steps to Reproduce:

1. Query any of those: Node, Nodes, Workload, Workloads
2. Specify a data range for which there is no data in metadata service
Actual API Response 
```
{
    "timestamp": "2024-10-30T09:13:08.714+00:00",
    "status": 500,
    "error": "Internal Server Error",
    "path": "/api/v1/clusters/kubernetes.local/nodes"
}
```
Expected API Response:

- empty result

**Comment by mattG117** [comment]
The bugs occurred because the pod wasn't up-to-date with the latest version (1.4.1 running, 1.4.2 latest).
Solved by triggering CI/CD again with new 1.4.3 tag.
