### ISSUE TITLE
[Power Measurement Framework] Component Demo

### ISSUE THREAD

**Issue by RafyMehany** [glaciation-heu/IceStream#98]
# Task:
Ensure the individual component is mature enough for a demonstration including:

## 1-Component Demo:
- **Description**: Provide a demo for your mature component.
- **Objectives**: Show the maturity of your component.

# Additional Information:
- You have the option to demonstrate your progress in your personal environment using either:
  - Video Recording
  - Images
- Any related documentation or information regarding the maturity, demonstration, or deployability should be communicated along with the submission.

# Acceptance Criteria:
- [ ] Demo shows the maturity of your service/component.

### Notes:
- **If you do not have anything to demo, please ensure that your component is deployable in your environment.**
- All documents and diagrams should be placed in  markdown `.md` files in the service directory <service>/docs
- you can delete this placeholder text if you got it.

**Comment by ktatarnikovhiro** [comment]
https://mefgovit.sharepoint.com/:v:/r/sites/glaciation/Documenti%20condivisi/General/7.%20Work%20Package%207%20-%20Validation%20and%20Use%20cases/T7.2/Milestone-5-Demo-2024-03-14/[monitoring-stack.webm](https://mefgovit.sharepoint.com/:v:/r/sites/glaciation/Documenti%20condivisi/General/7.%20Work%20Package%207%20-%20Validation%20and%20Use%20cases/T7.2/Milestone-5-Demo-2024-03-14/monitoring-stack.webm?csf=1&web=1&e=bfl0CM)?csf=1&web=1&e=bfl0CM
